"""Stage 7: Generate beautiful PDF from markdown report"""
from typing import Optional
from pathlib import Path
import markdown
from weasyprint import HTML, CSS
from backend.api.models.paper_model import LiteratureReviewReport
from backend.core.websocket_manager import manager
from datetime import datetime


# Academic CSS styling
ACADEMIC_CSS = """
@page {
    size: A4;
    margin: 2.5cm;
}

body {
    font-family: 'Georgia', 'Times New Roman', serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
}

h1 {
    font-size: 24pt;
    color: #1a1a1a;
    border-bottom: 3px solid #CC8844;
    padding-bottom: 10px;
    margin-top: 0;
    margin-bottom: 20px;
}

h2 {
    font-size: 18pt;
    color: #2c2c2c;
    border-bottom: 2px solid #E6A966;
    padding-bottom: 6px;
    margin-top: 30px;
    margin-bottom: 15px;
}

h3 {
    font-size: 14pt;
    color: #3d3d3d;
    margin-top: 20px;
    margin-bottom: 10px;
}

p {
    text-align: justify;
    margin-bottom: 10px;
}

ul, ol {
    margin-left: 20px;
    margin-bottom: 15px;
}

li {
    margin-bottom: 8px;
}

strong {
    color: #1a1a1a;
    font-weight: 600;
}

a {
    color: #CC8844;
    text-decoration: none;
}

.header {
    text-align: center;
    margin-bottom: 40px;
    padding: 20px;
    background: linear-gradient(135deg, #F5EDD6 0%, #E6A966 100%);
    border-radius: 10px;
}

.metadata {
    font-size: 10pt;
    color: #666;
    margin-top: 30px;
    padding-top: 15px;
    border-top: 1px solid #ddd;
}

.footer {
    text-align: center;
    font-size: 9pt;
    color: #888;
    margin-top: 50px;
}

code {
    background-color: #f5f5f5;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    font-size: 10pt;
}
"""


async def execute(session_id: str, report: LiteratureReviewReport, output_dir: Path) -> str:
    """Generate PDF from literature review report"""
    
    await manager.send_stage_update(
        session_id,
        stage=7,
        progress=20,
        message="Converting markdown to HTML..."
    )
    
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Add header with metadata
    header_html = f"""
    <div class="header">
        <h1>Academic Literature Review</h1>
        <p><strong>Query:</strong> {report.query}</p>
        <p><strong>Generated:</strong> {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}</p>
        <p><strong>Papers Analyzed:</strong> {report.total_papers}</p>
    </div>
    """
    
    # Convert markdown to HTML
    md_content = report.synthesis
    html_content = markdown.markdown(md_content, extensions=['extra', 'nl2br', 'sane_lists'])
    
    await manager.send_stage_update(
        session_id,
        stage=7,
        progress=50,
        message="Applying academic styling..."
    )
    
    # Add footer with metadata
    footer_html = f"""
    <div class="footer">
        <p>Generated by LitReview System | {report.generated_at.strftime('%Y-%m-%d')}</p>
        <p>{report.total_papers} papers | {len(report.papers_by_theme)} themes | {len(report.papers_by_methodology)} methodologies</p>
    </div>
    """
    
    # Combine into full HTML document
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Literature Review - {report.query}</title>
    </head>
    <body>
        {header_html}
        {html_content}
        {footer_html}
    </body>
    </html>
    """
    
    await manager.send_stage_update(
        session_id,
        stage=7,
        progress=70,
        message="Generating PDF..."
    )
    
    # Generate PDF
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_filename = f"literature_review_{timestamp}.pdf"
    pdf_path = output_dir / pdf_filename
    
    try:
        HTML(string=full_html).write_pdf(
            pdf_path,
            stylesheets=[CSS(string=ACADEMIC_CSS)]
        )
    except Exception as e:
        # Fallback: save as HTML if PDF generation fails
        html_path = output_dir / f"literature_review_{timestamp}.html"
        html_path.write_text(full_html, encoding='utf-8')
        
        await manager.send_stage_complete(
            session_id,
            stage=7,
            result={
                "pdf_generated": False,
                "html_fallback": str(html_path),
                "error": str(e)
            }
        )
        
        return str(html_path)
    
    await manager.send_stage_complete(
        session_id,
        stage=7,
        result={
            "pdf_generated": True,
            "pdf_path": str(pdf_path),
            "file_size": pdf_path.stat().st_size
        }
    )
    
    return str(pdf_path)
